[phases.setup]
nixPkgs = ['chromium']

[phases.install]
cmds = ['rm -f package-lock.json && npm install --omit=dev']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'npm start' 