[phases.setup]
nixPkgs = ['chromium', 'cairo', 'pango', 'libjpeg', 'libpng', 'giflib', 'librsvg']

[phases.install]
cmds = ['npm install --omit=dev']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production' 